---
host:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/spring-workshop-db
    username: sa
    password: 
  flyway:
    url: jdbc:h2:file:~/spring-workshop-db
    user: sa
    password:
    locations: classpath:db/migration
    
